spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver #org.h2.Driver
    url: jdbc:mysql://localhost:3306/ecommerceInventory?useSSL=false #jdbc:h2:mem:mydb #testdb
    username: root
    password: A1b2c347

token:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
